version: '3'

services:
  node:
    image: node:16.14
    container_name: trybecar
    tty: true
    stdin_open: true
    command: bash
    restart: always
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
    depends_on:
      - database
    ports:
      - 3001:3001
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: mysqlpass
      MYSQL_PORT: 3306
      MYSQL_HOST: database
      PORT: 3001
  
  database:
    image: mysql:8.0.29
    container_name: trybecar_db
    environment:
      MYSQL_ROOT_PASSWORD: mysqlpass
      MYSQL_DATABASE: trybecardb
    ports:
      - 3306:3306
    volumes:
      - ./script.sql:/docker-entrypoint-initdb.d/script.sql
