version: '3'
services:
  blog:
    image: ghost:1-alpine
    ports:
      - 2368:2368
    environment:
      database__client: mysql
      database__connection__host: db
      database__connection__user: root
      database__connection__password: password
      database__connection__database: ghost
    depends_on:
      db:
        condition: service_healthy
    networks:
      - net_blog

  db:
    image: mysql:5.7.40
    environment:
      MYSQL_ROOT_PASSWORD: password
    networks:
      - net_blog
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 3
networks:
  net_blog: