version: '3'

services:
  mysql:
    container_name: mysql-docker
    image: mysql:5.7
    ports:
      - 3306:3306
      - 33060:33060
    networks:
      - mysql-network
    environment:
      MYSQL_ROOT_PASSWORD: '@mysql2022'
      # MYSQL_INITDB_SKIP_TZINFO: 'America/Sao_Paulo' ou comando no terminal TZ='America/Sao_Paulo'; export TZ
networks:
  mysql-network: